import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { requireCourseStaff } from "@/lib/auth";
import { formatDateTime } from "@/lib/format";
import { addClinicalEvent, addClinicalNote, addLabResult, addPrescriptionItem, addVitalSign } from "./actions";

export default async function EpisodeAdminPage({ params }: { params: Promise<{ courseId: string; patientId: string; episodeId: string }> }) {
  const { courseId, patientId, episodeId } = await params;
  const { supabase, user } = await requireCourseStaff(courseId);
  const [{ data: episode }, { data: profile }] = await Promise.all([
    supabase.from("case_episodes").select(`
      id,week_no,title,summary,branch_key,release_at,due_at,is_final,
      patient:simulated_patients(id,code,display_name),
      vital_signs(*),lab_results(*),clinical_notes(*),clinical_events(*),
      prescriptions(id,status,prescribed_at,prescription_items(*)),teacher_notes:episode_teacher_notes(note)
    `).eq("id", episodeId).eq("patient_id", patientId).single(),
    supabase.from("profiles").select("full_name,email").eq("id", user.id).single(),
  ]);
  if (!episode) return <AppShell userName={profile?.full_name || profile?.email}><div className="alert">Episódio não encontrado.</div></AppShell>;
  const rxItems = (episode.prescriptions || []).flatMap((rx:any) => rx.prescription_items || []);
  return (
    <AppShell userName={profile?.full_name || profile?.email}>
      <section className="hero"><div><div className="eyebrow">Semana {episode.week_no} · {episode.branch_key}</div><h1>{episode.title}</h1><p>{episode.summary}</p></div><Link className="btn btn-secondary" href={`/professor/courses/${courseId}/cases/${patientId}`}>Voltar ao paciente</Link></section>
      {episode.teacher_notes?.[0]?.note ? <div className="note" style={{marginBottom:20}}><strong>Nota exclusiva do professor:</strong> {episode.teacher_notes[0].note}</div> : null}
      <div className="grid grid-2" style={{marginBottom:24}}>
        <section className="card"><h2>Sinais vitais</h2><form action={addVitalSign.bind(null,courseId,patientId,episodeId)} className="form-grid">
          <div className="field span-2"><label>Data/hora</label><input className="input" name="measured_at" type="datetime-local" required /></div>
          <div className="field"><label>FC</label><input className="input" name="heart_rate" type="number" /></div><div className="field"><label>FR</label><input className="input" name="respiratory_rate" type="number" /></div>
          <div className="field"><label>PA sistólica</label><input className="input" name="systolic_bp" type="number" /></div><div className="field"><label>PA diastólica</label><input className="input" name="diastolic_bp" type="number" /></div>
          <div className="field"><label>SpO₂ (%)</label><input className="input" name="spo2" type="number" step="0.1" /></div><div className="field"><label>Temperatura (°C)</label><input className="input" name="temperature_c" type="number" step="0.1" /></div>
          <div className="field"><label>Dor (0–10)</label><input className="input" name="pain_score" type="number" min="0" max="10" /></div><div><button className="btn" type="submit">Adicionar</button></div>
        </form><div className="divider"/>{(episode.vital_signs || []).length ? <div className="table-wrap"><table><thead><tr><th>Hora</th><th>FC</th><th>PA</th><th>SpO₂</th><th>T</th></tr></thead><tbody>{(episode.vital_signs || []).map((v:any)=><tr key={v.id}><td>{formatDateTime(v.measured_at)}</td><td>{v.heart_rate ?? "—"}</td><td>{v.systolic_bp ?? "—"}/{v.diastolic_bp ?? "—"}</td><td>{v.spo2 ?? "—"}%</td><td>{v.temperature_c ?? "—"} °C</td></tr>)}</tbody></table></div> : <div className="empty">Sem sinais vitais.</div>}</section>
        <section className="card"><h2>Exames</h2><form action={addLabResult.bind(null,courseId,patientId,episodeId)} className="form-grid">
          <div className="field span-2"><label>Coleta</label><input className="input" name="collected_at" type="datetime-local" required /></div><div className="field"><label>Exame</label><input className="input" name="test_name" required /></div><div className="field"><label>Resultado</label><input className="input" name="value_text" required /></div><div className="field"><label>Unidade</label><input className="input" name="unit" /></div><div className="field"><label>Referência</label><input className="input" name="reference_range" /></div><div className="field"><label>Flag</label><select className="select" name="flag" defaultValue="normal"><option value="low">Baixo</option><option value="normal">Normal</option><option value="high">Alto</option><option value="critical">Crítico</option></select></div><div><button className="btn">Adicionar</button></div>
        </form><div className="divider"/>{(episode.lab_results || []).length ? <div className="table-wrap"><table><thead><tr><th>Exame</th><th>Resultado</th><th>Referência</th><th>Flag</th></tr></thead><tbody>{(episode.lab_results || []).map((l:any)=><tr key={l.id}><td>{l.test_name}</td><td><strong>{l.value_text}</strong> {l.unit}</td><td>{l.reference_range || "—"}</td><td><span className="badge">{l.flag}</span></td></tr>)}</tbody></table></div> : <div className="empty">Sem exames.</div>}</section>
      </div>
      <div className="grid grid-2" style={{marginBottom:24}}>
        <section className="card"><h2>Prescrição</h2><form action={addPrescriptionItem.bind(null,courseId,patientId,episodeId)} className="form-grid"><div className="field"><label>Medicamento</label><input className="input" name="drug" required /></div><div className="field"><label>Concentração</label><input className="input" name="concentration" /></div><div className="field"><label>Dose</label><input className="input" name="dose" required /></div><div className="field"><label>Via</label><input className="input" name="route" required /></div><div className="field"><label>Frequência</label><input className="input" name="frequency" required /></div><div className="field"><label>Duração</label><input className="input" name="duration" /></div><div className="field span-2"><label>Indicação</label><input className="input" name="indication" /></div><div><button className="btn">Adicionar</button></div></form><div className="divider"/>{rxItems.length ? <div className="stack">{rxItems.map((i:any)=><div key={i.id} className="card card-subtle"><strong>{i.drug}</strong><div>{i.concentration} · {i.dose} · {i.route} · {i.frequency}</div><div className="small muted">{i.indication || "Sem indicação registrada"}</div></div>)}</div> : <div className="empty">Sem itens prescritos.</div>}</section>
        <section className="card"><h2>Evolução multiprofissional</h2><form action={addClinicalNote.bind(null,courseId,patientId,episodeId)} className="stack"><div className="field"><label>Data/hora</label><input className="input" name="note_at" type="datetime-local" required /></div><div className="form-grid"><div className="field"><label>Profissão</label><input className="input" name="profession" placeholder="Medicina" required /></div><div className="field"><label>Tipo</label><input className="input" name="note_type" defaultValue="Evolução" /></div></div><div className="field"><label>Texto</label><textarea className="textarea" name="text" required /></div><button className="btn">Adicionar evolução</button></form><div className="divider"/><div className="timeline">{(episode.clinical_notes || []).map((n:any)=><div className="timeline-item" key={n.id}><div className="timeline-time">{formatDateTime(n.note_at)}</div><div className="timeline-content"><h4>{n.profession} · {n.note_type}</h4><div>{n.text}</div></div></div>)}</div></section>
      </div>
      <section className="card"><h2>Intercorrências / eventos críticos</h2><form action={addClinicalEvent.bind(null,courseId,patientId,episodeId)} className="form-grid"><div className="field"><label>Data/hora</label><input className="input" name="event_at" type="datetime-local" required /></div><div className="field"><label>Categoria</label><input className="input" name="category" defaultValue="Intercorrência" /></div><div className="field"><label>Gravidade</label><select className="select" name="severity" defaultValue="moderate"><option value="low">Baixa</option><option value="moderate">Moderada</option><option value="high">Alta</option><option value="critical">Crítica</option></select></div><div className="field"><label>Título</label><input className="input" name="title" required /></div><div className="field span-2"><label>Descrição</label><textarea className="textarea" name="description" required /></div><div><button className="btn">Adicionar evento</button></div></form><div className="divider"/><div className="stack">{(episode.clinical_events || []).map((e:any)=><div className="card card-subtle" key={e.id}><div className="row-between"><strong>{e.title}</strong><span className="badge">{e.severity}</span></div><div className="small muted">{formatDateTime(e.event_at)} · {e.category}</div><p>{e.description}</p></div>)}</div></section>
    </AppShell>
  );
}
